name: Auto Summary CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [12.x]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - run: node generateSummary.js
    - name: Commit files
      run: |
        git config --local user.email "1187985856@github.com"
        git config --local user.name "gentlemanhu"
        git add -A
        git commit -am "generate summary"
    - name: Push changes
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.OWN_GITHUB_TOKEN }}
