name: blog deploy

on:
  push:
    branches:
      - master

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master

      - name: Setup Node
        uses: actions/setup-node@v1
        with:
          node-version: '12.x'

#      - run: npm ci
      - run: npm install
      - run: npm run build

# https://github.com/peaceiris/actions-gh-pages
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3.2.0
        with: # 为预定义变量赋值
#          DEPLOY_KEY: ${{ secrets.ACTIONS_DEPLOY_KEY }}
          PERSONAL_TOKEN: ${{ secrets.PERSONAL_TOKEN }}
          EXTERNAL_REPOSITORY: woytu/woytu.github.io
          PUBLISH_BRANCH: master
          PUBLISH_DIR: ./docs
          FORCE_ORPHAN: true
          USER_NAME: woytu
          USER_EMAIL: admin@woytu.com
#        env: # 设置环境变量并赋值